development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: commute_info_development
  pool: 5
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: commute_info_test
  pool: 5
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  database: commu_info_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost
